'use client'
import {useEffect,useMemo,useState} from 'react'
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts'
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000'; const pct=v=>v==null?'—':(v*100).toFixed(1)+'%'
const JOB_LABELS={BACKTEST:'Backtest',SWEEP:'Parameter sweep',ROBUSTNESS:'Robustness',TRAIN_RIDGE:'Entraînement Ridge',TRAIN_HGB:'Entraînement HGB',DATA_REFRESH:'Mise à jour market data',SEC_REFRESH:'Mise à jour SEC',DAILY_PIPELINE:'Pipeline quotidien',PAPER_SNAPSHOT:'Snapshot Paper'}
const STATUS_LABELS={QUEUED:'En attente',RUNNING:'En cours',COMPLETED:'Terminé',FAILED:'Échec'}
export default function Home(){
 const [dash,setDash]=useState(null),[sys,setSys]=useState(null),[bt,setBt]=useState(null),[list,setList]=useState([]),[factors,setFactors]=useState([]),[positions,setPositions]=useState([]),[previewData,setPreviewData]=useState(null),[clock,setClock]=useState(null),[orders,setOrders]=useState([]),[jobs,setJobs]=useState([]),[strategies,setStrategies]=useState([]),[perf,setPerf]=useState(null),[datasets,setDatasets]=useState({}),[fills,setFills]=useState([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[msgType,setMsgType]=useState('info'),[actionLabel,setActionLabel]=useState('')
 const [cfg,setCfg]=useState({long_count:20,short_count:20,rebalance_days:5,commission_bps:6,slippage_bps:5,gross_exposure:2})
 const j=async(url,opt)=>{const r=await fetch(API+url,opt);const x=await r.json();if(!r.ok)throw Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail||x));return x}
 const load=async({silent=false}={})=>{if(!silent)setLoading(true);try{const [d,s,l,f,p,o,js,st,pe,ds,fi]=await Promise.all([j('/api/dashboard'),j('/api/system/status'),j('/api/backtests'),j('/api/factors/latest'),j('/api/paper/positions'),j('/api/paper/orders'),j('/api/jobs'),j('/api/strategies'),j('/api/paper/performance'),j('/api/system/datasets'),j('/api/paper/fills')]);setDash(d);setSys(s);setList(l);setFactors(f);setPositions(p);setOrders(o);setJobs(js);setStrategies(st);setPerf(pe);setDatasets(ds);setFills(fi);try{setClock(await j('/api/paper/clock'))}catch{}}catch(e){setMsg(e.message);setMsgType('error')}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{load();const t=setInterval(()=>load({silent:true}),5000);return()=>clearInterval(t)},[])
 const activeJobs=useMemo(()=>jobs.filter(x=>x.status==='QUEUED'||x.status==='RUNNING'),[jobs]); const latestActive=activeJobs[0]
 const act=async(label,fn)=>{setBusy(true);setActionLabel(label);setMsg(label);setMsgType('loading');try{const result=await fn();setMsg(label+' — terminé');setMsgType('success');return result}catch(e){setMsg(label+' — erreur : '+e.message);setMsgType('error');throw e}finally{setBusy(false);setActionLabel('');load({silent:true})}}
 const run=()=>act('Backtest en cours…',async()=>setBt(await j('/api/backtests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)}))).catch(()=>{})
 const queue=async(path,label='Job')=>{setMsg(label+' — mise en file d’attente…');setMsgType('loading');try{const x=await j(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});setMsg(label+' ajouté à la file — suivi dans Background Jobs');setMsgType('success');await load({silent:true})}catch(e){setMsg(label+' — erreur : '+e.message);setMsgType('error')}}
 const preview=()=>act('Préparation du rebalance…',async()=>{const x=await j('/api/paper/rebalance/preview?n='+cfg.long_count);setPreviewData(x);setMsg('Preview prête : '+x.proposed_orders.length+' actions — Risk Gate '+(x.risk.passed?'PASS':'BLOCK'));setMsgType(x.risk.passed?'success':'warning');return x}).catch(()=>{})
 const execute=()=>{if(!confirm('Envoyer le rebalance au compte ALPACA PAPER ?'))return;act('Envoi des ordres PAPER…',async()=>{const x=await j('/api/paper/rebalance/execute?n='+cfg.long_count,{method:'POST'});setMsg(x.status+': '+x.orders.length+' actions soumises');setMsgType('success');return x}).catch(()=>{})}
 if(loading&&!dash)return <main className="wrap"><div className="loadingScreen"><div className="spinner"/><h2>Chargement de Quant Lab…</h2><div className="muted">Connexion à l’API et récupération des derniers résultats.</div></div></main>
 return <main className="wrap"><div className="head"><div><h1>Quant Lab <span className="muted">V1</span></h1><div className="muted">Research → Backtest → Validation → Alpaca Paper</div></div><div><b>{sys?.data_mode?.toUpperCase()}</b> / PAPER</div></div>
 {(msg||latestActive)&&<div className={'statusBanner '+(latestActive?'loading':msgType)}><div>{(latestActive||msgType==='loading')&&<span className="spinner small"/>}</div><div className="grow"><b>{latestActive?((JOB_LABELS[latestActive.kind]||latestActive.kind)+' — '+(STATUS_LABELS[latestActive.status]||latestActive.status)):msg}</b>{latestActive&&<><div className="muted statusMeta">{latestActive.status==='QUEUED'?'Le worker démarrera ce job dès qu’il sera disponible.':'Progression : '+latestActive.progress+'%'}</div><div className="progress"><div style={{width:Math.max(3,latestActive.progress||0)+'%'}}/></div></>}</div></div>}
 <div className="grid"><div className="card"><div className="muted">Paper Equity</div><div className="big">${Number(dash?.broker?.equity||0).toLocaleString()}</div></div><div className="card"><div className="muted">Paper Return</div><div className="big">{pct(perf?.comparison?.paper_return)}</div></div><div className="card"><div className="muted">Dernier Sharpe</div><div className="big">{dash?.last_backtest?.sharpe??'—'}</div></div><div className="card"><div className="muted">Market</div><div className="big">{clock?.is_open?'OPEN':'CLOSED'}</div></div></div>
 <div className="two section"><div className="card"><h3>META US Strategy</h3><div className="row">{Object.entries(cfg).map(([k,v])=><label key={k} className="muted">{k}<br/><input type="number" step="any" value={v} onChange={e=>setCfg({...cfg,[k]:Number(e.target.value)})}/></label>)}</div><div className="row" style={{marginTop:16}}><button className="btn" onClick={run} disabled={busy}>{busy&&actionLabel.startsWith('Backtest')?'Backtest en cours…':'Run Backtest'}</button><button className="btn2" onClick={()=>queue('/api/jobs/backtest','Backtest')} disabled={busy}>Queue Backtest</button><button className="btn2" onClick={preview} disabled={busy}>{busy&&actionLabel.startsWith('Préparation')?'Chargement preview…':'Preview Rebalance'}</button><button className="btn2" disabled={busy} onClick={()=>act('Snapshot Paper en cours…',async()=>j('/api/paper/snapshot',{method:'POST'})).catch(()=>{})}>Snapshot</button>{sys?.paper_orders_enabled&&<button className="btn" onClick={execute} disabled={busy}>Execute PAPER</button>}</div></div><div className="card"><h3>Système</h3><table><tbody><tr><td>Data</td><td>{sys?.data_mode}</td></tr><tr><td>Alpaca</td><td>{sys?.alpaca_configured?'connected':'not configured'}</td></tr><tr><td>Paper orders</td><td>{sys?.paper_orders_enabled?'ARMED':'LOCKED'}</td></tr><tr><td>Paper auto</td><td>{sys?.paper_auto_enabled?'ON':'OFF'}</td></tr><tr><td>Tracked positions</td><td>{dash?.paper_positions??0}</td></tr></tbody></table></div></div>
 {perf?.history?.length>1&&<div className="card section"><h3>Paper Equity & Backtest Comparison</h3><div className="row"><div className="card">Paper return<br/><b>{pct(perf.comparison.paper_return)}</b></div><div className="card">Backtest return<br/><b>{pct(perf.comparison.backtest_return)}</b></div><div className="card">Gap<br/><b>{pct(perf.comparison.return_gap)}</b></div><div className="card">Snapshots<br/><b>{perf.comparison.paper_snapshots}</b></div></div><div style={{height:260}}><ResponsiveContainer width="100%" height="100%"><LineChart data={perf.history}><XAxis dataKey="created_at" hide/><YAxis domain={['auto','auto']}/><Tooltip/><Line dataKey="equity" dot={false}/></LineChart></ResponsiveContainer></div></div>}
 {bt&&<div className="card section"><h3>Equity Curve</h3><div className="resultNotice success">Backtest terminé — Sharpe {bt.metrics?.sharpe??'—'} · CAGR {pct(bt.metrics?.cagr)} · Max DD {pct(bt.metrics?.max_drawdown)}</div><div style={{height:280}}><ResponsiveContainer width="100%" height="100%"><LineChart data={bt.equity_curve}><XAxis dataKey="date" minTickGap={50}/><YAxis domain={['auto','auto']}/><Tooltip/><Line dataKey="equity" dot={false}/></LineChart></ResponsiveContainer></div></div>}
 <div className="two section"><div className="card"><h3>Latest Ranking</h3><table><thead><tr><th>#</th><th>Symbol</th><th>Score</th><th>Momentum</th><th>News</th></tr></thead><tbody>{factors.slice(0,20).map((r,i)=><tr key={r.symbol}><td>{i+1}</td><td>{r.symbol}</td><td>{r.meta_score}</td><td>{r.momentum_12_1_rank}</td><td>{r.news_raw_rank}</td></tr>)}</tbody></table></div><div className="card"><h3>Paper Positions</h3><table><tbody>{positions.slice(0,25).map(r=><tr key={r.symbol}><td>{r.symbol}</td><td className={r.side==='LONG'?'positive':'negative'}>{r.side}</td><td>{pct(r.weight)}</td><td>{Number(r.score).toFixed(3)}</td></tr>)}</tbody></table></div></div>
 <div className="two section"><div className="card"><h3>Strategy Registry</h3><table><thead><tr><th>Name</th><th>Version</th><th>Status</th></tr></thead><tbody>{strategies.map(s=><tr key={s.id}><td>{s.name}</td><td>v{s.version}</td><td>{s.status}</td></tr>)}</tbody></table></div><div className="card"><h3>Background Jobs</h3>{!jobs.length?<div className="empty">Aucun job lancé.</div>:<table><thead><tr><th>Kind</th><th>Status</th><th>Progress</th></tr></thead><tbody>{jobs.slice(0,15).map(x=><tr key={x.job_key}><td>{JOB_LABELS[x.kind]||x.kind}</td><td><span className={'pill '+x.status.toLowerCase()}>{STATUS_LABELS[x.status]||x.status}</span>{x.error&&<div className="jobError">{x.error}</div>}</td><td><div className="progress compact"><div style={{width:(x.progress||0)+'%'}}/></div><small>{x.progress}%</small></td></tr>)}</tbody></table>}</div></div>
 {previewData&&<div className="card section"><h3>Rebalance Preview & Risk Gate</h3><div className="row">{previewData.risk.checks.map(x=><div className="card" key={x.name}><small>{x.name}</small><br/><b className={x.ok?'positive':'negative'}>{x.ok?'PASS':'BLOCK'}</b></div>)}</div><table><tbody>{previewData.proposed_orders.slice(0,50).map((o,i)=><tr key={o.symbol+i}><td>{o.symbol}</td><td>{o.action}</td><td>${o.current_notional}</td><td>→ ${o.target_notional}</td><td>${o.delta}</td></tr>)}</tbody></table></div>}
 <div className="two section"><div className="card"><h3>Dataset / Feature Versions</h3><table><tbody>{Object.entries(datasets||{}).map(([k,v])=><tr key={k}><td>{k}</td><td>{v.version||v.status||'—'}</td><td>{v.latest||v.updated_at||''}</td></tr>)}</tbody></table><button className="btn2" disabled={busy||activeJobs.some(x=>x.kind==='DAILY_PIPELINE')} onClick={async()=>{setMsg('Pipeline quotidien — mise en file d’attente…');setMsgType('loading');try{const x=await j('/api/jobs/daily-pipeline?force_market=true',{method:'POST'});setMsg('Pipeline quotidien ajouté à la file : '+x.job_key);setMsgType('success');load({silent:true})}catch(e){setMsg('Pipeline quotidien — erreur : '+e.message);setMsgType('error')}}>{activeJobs.some(x=>x.kind==='DAILY_PIPELINE')?'Pipeline en cours…':'Run Daily Pipeline'}</button></div><div className="card"><h3>Recent Paper Fills</h3><table><tbody>{fills.slice(0,20).map(x=><tr key={x.id}><td>{x.symbol}</td><td>{x.side}</td><td>{x.qty}</td><td>${Number(x.price).toFixed(2)}</td><td>{x.event}</td></tr>)}</tbody></table></div></div>
 <div className="two section"><div className="card"><h3>Tracked Paper Orders</h3><table><tbody>{orders.slice(0,20).map(o=><tr key={o.client_order_id}><td>{o.symbol}</td><td>{o.side}</td><td>${Number(o.notional).toFixed(0)}</td><td>{o.status}</td></tr>)}</tbody></table></div><div className="card"><h3>Backtests</h3><table><tbody>{list.slice(0,20).map(r=><tr key={r.id}><td>#{r.id}</td><td>{r.strategy}</td><td>{pct(r.cagr)}</td><td>{r.sharpe}</td><td>{pct(r.max_drawdown)}</td></tr>)}</tbody></table></div></div></main>
}
