'use client'
import {useEffect,useState} from 'react'
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts'
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000'; const pct=v=>v==null?'—':(v*100).toFixed(1)+'%'
export default function Home(){
 const [dash,setDash]=useState(null),[sys,setSys]=useState(null),[bt,setBt]=useState(null),[list,setList]=useState([]),[factors,setFactors]=useState([]),[positions,setPositions]=useState([]),[previewData,setPreviewData]=useState(null),[clock,setClock]=useState(null),[orders,setOrders]=useState([]),[jobs,setJobs]=useState([]),[strategies,setStrategies]=useState([]),[perf,setPerf]=useState(null),[datasets,setDatasets]=useState({}),[fills,setFills]=useState([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('')
 const [cfg,setCfg]=useState({long_count:20,short_count:20,rebalance_days:5,commission_bps:6,slippage_bps:5,gross_exposure:2})
 const j=async(url,opt)=>{const r=await fetch(API+url,opt);const x=await r.json();if(!r.ok)throw Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail||x));return x}
 const load=async()=>{try{const [d,s,l,f,p,o,js,st,pe,ds,fi]=await Promise.all([j('/api/dashboard'),j('/api/system/status'),j('/api/backtests'),j('/api/factors/latest'),j('/api/paper/positions'),j('/api/paper/orders'),j('/api/jobs'),j('/api/strategies'),j('/api/paper/performance'),j('/api/system/datasets'),j('/api/paper/fills')]);setDash(d);setSys(s);setList(l);setFactors(f);setPositions(p);setOrders(o);setJobs(js);setStrategies(st);setPerf(pe);setDatasets(ds);setFills(fi);try{setClock(await j('/api/paper/clock'))}catch{}}catch(e){setMsg(e.message)}}
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[])
 const act=async(fn)=>{setBusy(true);setMsg('');try{await fn()}catch(e){setMsg(e.message)}finally{setBusy(false);load()}}
 const run=()=>act(async()=>setBt(await j('/api/backtests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)})))
 const queue=(path)=>act(async()=>{const x=await j(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg)});setMsg(`Job ${x.kind} queued: ${x.job_key}`)})
 const preview=()=>act(async()=>{const x=await j('/api/paper/rebalance/preview?n='+cfg.long_count);setPreviewData(x);setMsg(`Preview: ${x.proposed_orders.length} actions, risk gate ${x.risk.passed?'PASS':'BLOCK'}`)})
 const execute=()=>{if(!confirm('Envoyer le rebalance au compte ALPACA PAPER ?'))return;act(async()=>{const x=await j('/api/paper/rebalance/execute?n='+cfg.long_count,{method:'POST'});setMsg(`${x.status}: ${x.orders.length} actions soumises`)})}
 return <main className="wrap"><div className="head"><div><h1>Quant Lab <span className="muted">V1</span></h1><div className="muted">Research → Backtest → Validation → Alpaca Paper</div></div><div><b>{sys?.data_mode?.toUpperCase()}</b> / PAPER</div></div>
 {msg&&<div className="card section">{msg}</div>}
 <div className="grid"><div className="card"><div className="muted">Paper Equity</div><div className="big">${Number(dash?.broker?.equity||0).toLocaleString()}</div></div><div className="card"><div className="muted">Paper Return</div><div className="big">{pct(perf?.comparison?.paper_return)}</div></div><div className="card"><div className="muted">Dernier Sharpe</div><div className="big">{dash?.last_backtest?.sharpe??'—'}</div></div><div className="card"><div className="muted">Market</div><div className="big">{clock?.is_open?'OPEN':'CLOSED'}</div></div></div>
 <div className="two section"><div className="card"><h3>META US Strategy</h3><div className="row">{Object.entries(cfg).map(([k,v])=><label key={k} className="muted">{k}<br/><input type="number" step="any" value={v} onChange={e=>setCfg({...cfg,[k]:Number(e.target.value)})}/></label>)}</div><div className="row" style={{marginTop:16}}><button className="btn" onClick={run} disabled={busy}>Run Backtest</button><button className="btn2" onClick={()=>queue('/api/jobs/backtest')} disabled={busy}>Queue Backtest</button><button className="btn2" onClick={preview} disabled={busy}>Preview Rebalance</button><button className="btn2" onClick={()=>act(async()=>{await j('/api/paper/snapshot',{method:'POST'});setMsg('Paper snapshot saved')})}>Snapshot</button>{sys?.paper_orders_enabled&&<button className="btn" onClick={execute} disabled={busy}>Execute PAPER</button>}</div></div><div className="card"><h3>Système</h3><table><tbody><tr><td>Data</td><td>{sys?.data_mode}</td></tr><tr><td>Alpaca</td><td>{sys?.alpaca_configured?'connected':'not configured'}</td></tr><tr><td>Paper orders</td><td>{sys?.paper_orders_enabled?'ARMED':'LOCKED'}</td></tr><tr><td>Paper auto</td><td>{sys?.paper_auto_enabled?'ON':'OFF'}</td></tr><tr><td>Tracked positions</td><td>{dash?.paper_positions??0}</td></tr></tbody></table></div></div>
 {perf?.history?.length>1&&<div className="card section"><h3>Paper Equity & Backtest Comparison</h3><div className="row"><div className="card">Paper return<br/><b>{pct(perf.comparison.paper_return)}</b></div><div className="card">Backtest return<br/><b>{pct(perf.comparison.backtest_return)}</b></div><div className="card">Gap<br/><b>{pct(perf.comparison.return_gap)}</b></div><div className="card">Snapshots<br/><b>{perf.comparison.paper_snapshots}</b></div></div><div style={{height:260}}><ResponsiveContainer width="100%" height="100%"><LineChart data={perf.history}><XAxis dataKey="created_at" hide/><YAxis domain={['auto','auto']}/><Tooltip/><Line dataKey="equity" dot={false}/></LineChart></ResponsiveContainer></div></div>}
 {bt&&<div className="card section"><h3>Equity Curve</h3><div style={{height:280}}><ResponsiveContainer width="100%" height="100%"><LineChart data={bt.equity_curve}><XAxis dataKey="date" minTickGap={50}/><YAxis domain={['auto','auto']}/><Tooltip/><Line dataKey="equity" dot={false}/></LineChart></ResponsiveContainer></div></div>}
 <div className="two section"><div className="card"><h3>Latest Ranking</h3><table><thead><tr><th>#</th><th>Symbol</th><th>Score</th><th>Momentum</th><th>News</th></tr></thead><tbody>{factors.slice(0,20).map((r,i)=><tr key={r.symbol}><td>{i+1}</td><td>{r.symbol}</td><td>{r.meta_score}</td><td>{r.momentum_12_1_rank}</td><td>{r.news_raw_rank}</td></tr>)}</tbody></table></div><div className="card"><h3>Paper Positions</h3><table><tbody>{positions.slice(0,25).map(r=><tr key={r.symbol}><td>{r.symbol}</td><td className={r.side==='LONG'?'positive':'negative'}>{r.side}</td><td>{pct(r.weight)}</td><td>{Number(r.score).toFixed(3)}</td></tr>)}</tbody></table></div></div>
 <div className="two section"><div className="card"><h3>Strategy Registry</h3><table><thead><tr><th>Name</th><th>Version</th><th>Status</th></tr></thead><tbody>{strategies.map(s=><tr key={s.id}><td>{s.name}</td><td>v{s.version}</td><td>{s.status}</td></tr>)}</tbody></table></div><div className="card"><h3>Background Jobs</h3><table><thead><tr><th>Kind</th><th>Status</th><th>Progress</th></tr></thead><tbody>{jobs.slice(0,15).map(x=><tr key={x.job_key}><td>{x.kind}</td><td>{x.status}</td><td>{x.progress}%</td></tr>)}</tbody></table></div></div>
 {previewData&&<div className="card section"><h3>Rebalance Preview & Risk Gate</h3><div className="row">{previewData.risk.checks.map(x=><div className="card" key={x.name}><small>{x.name}</small><br/><b className={x.ok?'positive':'negative'}>{x.ok?'PASS':'BLOCK'}</b></div>)}</div><table><tbody>{previewData.proposed_orders.slice(0,50).map((o,i)=><tr key={o.symbol+i}><td>{o.symbol}</td><td>{o.action}</td><td>${o.current_notional}</td><td>→ ${o.target_notional}</td><td>${o.delta}</td></tr>)}</tbody></table></div>}
 <div className="two section"><div className="card"><h3>Dataset / Feature Versions</h3><table><tbody>{Object.entries(datasets||{}).map(([k,v])=><tr key={k}><td>{k}</td><td>{v.version||v.status||'—'}</td><td>{v.latest||v.updated_at||''}</td></tr>)}</tbody></table><button className="btn2" onClick={()=>act(async()=>{const x=await j('/api/jobs/daily-pipeline?force_market=true',{method:'POST'});setMsg(`Daily pipeline queued: ${x.job_key}`)})}>Run Daily Pipeline</button></div><div className="card"><h3>Recent Paper Fills</h3><table><tbody>{fills.slice(0,20).map(x=><tr key={x.id}><td>{x.symbol}</td><td>{x.side}</td><td>{x.qty}</td><td>${Number(x.price).toFixed(2)}</td><td>{x.event}</td></tr>)}</tbody></table></div></div>
 <div className="two section"><div className="card"><h3>Tracked Paper Orders</h3><table><tbody>{orders.slice(0,20).map(o=><tr key={o.client_order_id}><td>{o.symbol}</td><td>{o.side}</td><td>${Number(o.notional).toFixed(0)}</td><td>{o.status}</td></tr>)}</tbody></table></div><div className="card"><h3>Backtests</h3><table><tbody>{list.slice(0,20).map(r=><tr key={r.id}><td>#{r.id}</td><td>{r.strategy}</td><td>{pct(r.cagr)}</td><td>{r.sharpe}</td><td>{pct(r.max_drawdown)}</td></tr>)}</tbody></table></div></div></main>
}
